apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: linksnap-beta
resources:
  - ../../base
  - namespace.yaml
  - secrets.yaml

images:
  - name: tanaymondal/linksnap-backend
    newName: tanaymondal/linksnap-backend-beta
    newTag: beta
  - name: tanaymondal/linksnap-frontend
    newName: tanaymondal/linksnap-frontend-beta
    newTag: beta
